spring.application.name=demo
  spring.thymeleaf.cache=false
  spring.thymeleaf.prefix=classpath:/templates/
  spring.thymeleaf.suffix=.html



#spring.application.name: アプリケーション名を指定します。

#spring.thymeleaf.cache=false: テンプレートキャッシュを無効化（開発時のみ）。

#spring.thymeleaf.prefix / suffix: テンプレートファイルのパスと拡張子を指定します。

